@startuml Diagrama ER - Concesionario Zaru

skinparam linetype ortho

entity Empresa {
    nit <<PK>>
    nombre
    direccion
    telefono
    correo
}

entity RegistroEmpresa {
    nit <<PK, FK>>
    fecha_registro
    tipo_empresa
}

entity Concesionario {
    nit <<PK, FK>>
    tipo_automoviles
}

entity ServicioOficial {
    nit <<PK, FK>>
    concesionario_nit <<FK>>
}

entity Marca {
    nombre <<PK>>
}

entity MarcaConcesionario {
    concesionario_nit <<PK, FK>>
    marca_nombre <<PK, FK>>
}

entity Modelo {
    id <<PK>>
    marca_nombre <<FK>>
    nombre 
    precio
}

entity FichaTecnica {
    modelo_id <<PK, FK>>
    cilindraje
    potencia
    torque
    motor
    combustible
    carroceria
    color_id <<FK>>
}

entity Equipamiento {
    id <<PK>>
    modelo_id <<FK>>
    accesorio_id <<FK>>
    es_extra
    precio
}

entity Accesorio {
    id <<PK>>
    nombre
}

entity Automovil {
    numero_bastidor <<PK>>
    modelo_id <<FK>>
    registro_empresa_nit <<FK>>
    estado
}

entity Venta {
    id <<PK>>
    numero_bastidor <<FK Unique>>
    cedula_vendedor <<FK>>
    cedula_cliente <<FK>>
    fecha_entrega
    fecha_venta
    matricula_asignada <<Unique>>
    es_encargo
    metodo_pago
    precio_venta
}

entity ExtraVenta {
    venta_id <<PK, FK>>
    equipamiento_id <<PK, FK>>
    precio
}

entity Persona {
    cedula <<PK>>
    nombre
    apellido
    direccion
    telefono
    correo
}

entity Usuario {
    nombre_usuario <<PK>>
    contrasena
    cedula <<FK>>
    tipo
}

entity Vendedor {
    cedula <<PK, FK>>
    registro_empresa_nit <<FK>>
}

entity Cliente {
    cedula <<PK, FK>>
    cantidad_compras
}

entity Descuento {
    id <<PK>>
    nombre
    porcentaje
    descripcion
}

entity DescuentoAplicado {
    automovil_id <<PK, FK>>
    descuento_id <<PK, FK>>
}

entity Color {
    id <<PK>>
    nombre
}

hide methods

Empresa ||--|| RegistroEmpresa
RegistroEmpresa ||--o| Concesionario
RegistroEmpresa ||--o| ServicioOficial
RegistroEmpresa ||--o{ Vendedor
Concesionario ||--o{ ServicioOficial
Concesionario ||--|{ MarcaConcesionario
Marca ||--o{ MarcaConcesionario
Marca ||--o{ Modelo
Modelo ||--o{ Automovil
Modelo ||--|| FichaTecnica
Modelo ||--|{ Equipamiento
Accesorio |o--|{ Equipamiento
Automovil ||--o| Venta
Equipamiento ||--o{ ExtraVenta
Venta ||--o{ ExtraVenta
Vendedor ||--o{ Venta
Cliente ||--o{ Venta
Automovil ||--o{ DescuentoAplicado
Descuento ||-right-o{ DescuentoAplicado
RegistroEmpresa ||--o{ Automovil
Persona ||--o| Usuario
Persona ||--o| Vendedor
Persona ||--o| Cliente
Color ||--o{ FichaTecnica
@enduml
